language: go
go:
  - 1.11.x
env:
  - GO111MODULE=on
before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/axw/gocov/gocov
  - go get github.com/securego/gosec/cmd/gosec
services:
  - mongodb
script:
  - gosec ./...
  - go test -v  ./... -covermode=count -coverprofile=coverage.out
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
