version: '2.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: statuspage_mongo
    
  statuspage:
    build: ./
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - MONGO_URI=mongo
      - GIN_MODE=debug
