package models

import "time"

//PrometheusIncomingWebhook is the payload sent from the Prometheus AlertManager
type PrometheusIncomingWebhook struct {
	Alerts []PrometheusAlerts `json:"alerts" binding:"required"`
}

//PrometheusAlerts represents a special structure of Alert generated by Prometheus rules
type PrometheusAlerts struct {
	Status          string          `json:"status"`
	PrometheusLabel PrometheusLabel `json:"labels,omitempty" binding:"required"`
	Component       Component       `json:"annotations,omitempty" binding:"required"`
	StartsAt        time.Time       `json:"startsAt,omitempty"`
	EndsAt          time.Time       `json:"endsAt"`
	GeneratorURL    string          `json:"generatorURL,omitempty"`
}

type PrometheusLabel struct {
	Status       string    `json:"status" binding:"required"`
	Date         time.Time `json:"occurrence_date" binding:"required"`
	ComponentRef string    `json:"component_ref" bson:"component_ref" binding:"required"`
}
